{
 "title": "SecuritySpy",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cameras",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "securityspy_server_camera_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "securityspy_server_cpu_usage_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "securityspy_server_memory_pressure",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Camera Connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "securityspy_camera_connected", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Camera Mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "securityspy_camera_mode", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Time Since Last Frame",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "securityspy_camera_time_since_last_frame_seconds",
     "legendFormat": "{{camera_name}}"
    }
   ]
  },
  {
   "title": "Number of Recordings (log10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "log10(securityspy_camera_num_files)",
     "legendFormat": "{{camera_name}}"
    }
   ]
  },
  {
   "title": "Recorded Bytes (log10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "log10(securityspy_camera_recorded_bytes)",
     "legendFormat": "{{camera_name}}"
    }
   ]
  },
  {
   "title": "Newest Recording Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "securityspy_newest_recording_age_seconds",
     "legendFormat": "{{camera_name}}"
    }
   ]
  },
  {
   "title": "Oldest Recording Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "securityspy_oldest_recording_age_seconds",
     "legendFormat": "{{camera_name}}"
    }
   ]
  },
  {
   "title": "Camera FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "securityspy_camera_fps_FPS", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Time Since Last Motion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "securityspy_camera_time_since_last_motion_seconds",
     "legendFormat": "{{camera_name}}"
    }
   ]
  },
  {
   "title": "Motion Detection Capture",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "securityspy_camera_md_capture", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Motion Detection Enabled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "securityspy_camera_md_enable", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Mode M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "securityspy_camera_mode_m", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Mode C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "securityspy_camera_mode_c", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Image Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    { "expr": "securityspy_camera_height_PX", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Image Width",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    { "expr": "securityspy_camera_width_PX", "legendFormat": "{{camera_name}}" }
   ]
  }
 ]
}